# Generated by Django 6.1.1 on 2026-10-05 10:43

import invitations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=invitations.models.generate_short_code, max_length=12, unique=True, verbose_name='Уникален код (линк)')),
                ('invitation_name', models.CharField(max_length=120, verbose_name='Име/Обръщение на поканата')),
                ('max_guests', models.PositiveIntegerField(default=2, verbose_name='Позволен брой места')),
                ('is_attending', models.BooleanField(blank=True, null=True, verbose_name='Присъства ли')),
                ('attending_count', models.PositiveIntegerField(default=0, verbose_name='Потвърден брой гости')),
                ('dietary_notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Предпочитания за храна / Бележки')),
                ('music_wish', models.CharField(blank=True, max_length=200, null=True, verbose_name='Музикално желание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последна промяна')),
            ],
            options={
                'verbose_name': 'Гост',
                'verbose_name_plural': 'Гости',
            },
        ),
    ]
