# Generated by Django 6.1.1 on 2026-10-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отворена на'),
        ),
    ]
